spring:
  application:
    name: Supervision task runner
  liquibase:
    enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      definition: supervisionConsumer
    stream:
      default-binder: rabbit
      rabbit:
        bindings:
          supervision:
            consumer:
              autoBindDlq: false
              bindingRoutingKey: '#'
              bindQueue: true
              declareDlx: false
              declareExchange: true
              exchangeType: direct
              exchangeDurable: true
              exchangeAutoDelete: false
              exclusive: false
              queueNameGroupOnly: true
              republishToDlq: false
      bindings:
        supervision:
          destination: supervision
          group: supervision
          consumer:
            maxAttempts: 1
  jpa:
    show-sql: true
    properties:
      javax:
        persistence:
          sharedCache:
            #required - enable selective caching mode - only entities with @Cacheable annotation will use L2 cache.
            mode: ENABLE_SELECTIVE
      hibernate:
        javax:
          cache:
            missing_cache_strategy: create
        #optional - enable SQL statements formatting.
        format_sql: true
        #optional - generate statistics to check if L2/query cache is actually being used.
        generate_statistics: true
        cache:
          #required - turn on L2 cache.
          use_second_level_cache: true
          #optional - turn on query cache.
          use_query_cache: true
          region:
            #required - classpath to cache region factory.
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

persistence:
  cache-enabled: true
  batch-size: 100
  minimum-idle: 2
  maximum-pool-size: 10
  datasource:
    url: jdbc:postgresql://localhost:5432/supervision
    username: postgres
    password: postgres
    schema: supervision

module:
  datasource:
    url: jdbc:postgresql://localhost:5432/bi
    username: postgres
    password: postgres

logging:
  level:
    root: INFO
    #root: DEBUG
    fr.dademo: DEBUG
